Django_board/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('free/', include('free.urls')),
    path('', views.home, name='home')
]

board/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.shortcuts import redirect
app_name = 'board'
urlpatterns = [
    path('', views.BoardListView.as_view(), name='board_list'),
    path('<int:pk>/', views.board_detail_view, name='board_detail'),  # 게시글 상세보기
    path('write/', views.board_write_view, name='board_write'),
    path('<int:pk>/edit/', views.board_edit_view, name='board_edit'),
    path('<int:pk>/delete/', views.board_delete_view, name='board_delete'),
    path('download/<int:pk>', views.board_download_view, name='board_download'),
]


#media파일 접근 제한
def protected_file(request, path, document_root=None):
    messages.error(request, '접근불가')
    return redirect('/')


#urlpatterns에 Media File을 제공하는 패턴을 추가하고 protected_file 함수를 구현함으로써 url로 서버상의 MEDIA_ROOT에 접근하는것을 방지합니다.
urlpatterns += static(settings.MEDIA_URL, protected_file, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from .views import RegisterView, LoginView

urlpatterns = [
    path('', views.home, name='home'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

board/models.py
from django.db import models
from uuid import uuid4
import os
from django.conf import settings
from datetime import datetime
# Create your models here.

def get_file_path(instance, filename):
    date_path = datetime.now().strftime('%Y/%m/%d')
    uuidname = uuid4().hex
    return '/'.join(['upload_file/', date_path, uuidname])


class Board(models.Model):
    title = models.CharField(max_length=64, verbose_name='제목', null=True)
    content = models.TextField(verbose_name='내용')
    views = models.PositiveIntegerField(default=0,verbose_name='조회수')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    top_fixed = models.BooleanField(default=0, verbose_name='상단고정')#공지사항같은거, 페이지 넘겨도 상단 고정
    writer = models.ForeignKey('user.User', on_delete=models.SET_NULL, null=True)#user.User 작성자 불러오기
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')


    def __str__(self):
        return self.title

    class Meta:
        db_table = '게시글'
        verbose_name = '게시글'
        verbose_name_plural = '게시글'

    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Board, self).delete(*args, **kargs)

board/forms.py
from django import forms
from .models import Board


class BoardWriteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BoardWriteForm, self).__init__(*args, **kwargs)
        self.fields['title'].label ='제목'
        self.fields['title'].widget.attrs.update({
            'placeholder':'제목을 입력해주세요',
            'class': 'form-control',
            'autofocus': True,
        })

    class Meta:
        model = Board
        fields = ['title', 'content', 'top_fixed', 'upload_files']

board/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Board
from django.contrib import messages
from django.conf import settings
from django.db.models import Q
from user.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from .forms import BoardWriteForm
from user.models import User
import os
import urllib
from django.http import HttpResponse, Http404
import mimetypes


# Create your views here.

class BoardListView(ListView):
    model = Board
    paginate_by = 5  # 한페이지에 표시할 갯수
    template_name = 'board/board_list.html'
    context_object_name = 'board_list'

    # 게시글 검색 기능 구현

    def get_queryset(self):
        board_list = Board.objects.order_by('-id')
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_board_list = board_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__userid__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_board_list = board_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_board_list = board_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_board_list = board_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_board_list = board_list.filter(writer__userid__icontains=search_keyword)

                return search_board_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return board_list


    def get_context_data(self, **kwargs):  # 페이지네이터 기능
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        # 검색 타입, keyword, search_type 계속 유지하는 소스
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type

        board_fixed = Board.objects.filter(top_fixed=True).order_by('-registered_date')
        context['board_fixed'] = board_fixed
        return context


# 게시글 상세보기
@login_required
def board_detail_view(request, pk):
    board = get_object_or_404(Board, pk=pk)
    session_cookie = request.session['user']  # session_cookie 에 로그인한 아이디 삽입
    cookie_name = F'board_hits:{session_cookie}'  # cookie_name 에 session_cookie으로 접속한 사용자 아이디 삽입
    context = {
        'board': board,
    }
    response = render(request, 'board/board_detail.html', context)
    #본인 게시글 확인 context
    if request.user == board.writer:
        board_auth = True
    else:
        board_auth = False

    context = {
        'board': board,
        'board_auth': board_auth,
    }
    # 조회수 중복 방지 구현
    if request.COOKIES.get(cookie_name) is not None:
        cookies = request.COOKIES.get(cookie_name)  # 쿠키생성
        cookies_list = cookies.split('|')  # 로그인하면 쿠키들은 cookies_list 에 삽입
        if str(pk) not in cookies_list:
            response.set_cookie(cookie_name, cookies + f'|{pk}', expires=None)
            board.views += 1
            board.save()
            return response
    else:
        response.set_cookie(cookie_name, pk, expires=None)
        board.views += 1
        board.save()
        return response
    return render(request, 'board/board_detail.html', context)


# 게시글 작성하기
@login_required
def board_write_view(request):
    if request.method == 'POST':
        form = BoardWriteForm(request.POST, request.FILES)#파일 저장 request.FILES
        user = request.session['user']
        userid = User.objects.get(userid=user)

        if form.is_valid():
            board = form.save(commit=False)
            board.writer = userid
            if request.FILES:#파일 저장
                if 'upload_files' in request.FILES.keys():
                    board.filename = request.FILES['upload_files'].name
            board.save()
            return redirect('board:board_list')
    else:
        form = BoardWriteForm()

    return render(request, "board/board_write.html", {'form': form})


#게시글 수정
@login_required
def board_edit_view(request, pk):
    board = Board.objects.get(id=pk)

    if request.method == 'POST':
        if (board.writer == request.user or request.user.level == '0'):
            file_change_check = request.POST.get('fileChange', False)
            file_check = request.POST.get('upload_files_clear', False)
            if file_check or file_change_check:
                os.remove(os.path.join(settings.MEDIA_ROOT, board.upload_files.path))
            form = BoardWriteForm(request.POST, request.FILES, instance=board)
            if form.is_valid():
                board = form.save(commit=False)
                if request.FILES:
                    if 'upload_files' in request.FILES.keys():
                        board.filename = request.FILES['upload_files'].name
                board.save()
                messages.success(request, "수정 되었습니다.")
                return redirect('/board/' + str(pk))
    else:
        board = Board.objects.get(id=pk)
        if board.writer == request.user or request.user.level == '0':
            form = BoardWriteForm(instance=board)
            context = {
                'form': form,
                'edit': '수정하기',
            }
            if board.filename and board.upload_files:
                context['filename'] = board.filename
                context['file_url'] = board.upload_files.url
            return render(request, "board/board_write.html", context)
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
            return redirect('/board/' + str(pk))

#게시글 삭제
@login_required
def board_delete_view(request, pk):
    board = Board.objects.get(id=pk)#게시글의 pk값을 id로 받는다
    if board.writer == request.user or request.user.level == '0':
        board.delete()
        messages.success(request, '삭제되었습니다.')
        return redirect('/board/')
    else:
        messages.error(request, '본인 게시글이 아닙니다.')
        return redirect('/board/'+str(pk))

#다운로드 기능
@login_required
def board_download_view(request, pk):
    board = get_object_or_404(Board, pk=pk)
    url = board.upload_files.url[1:]
    file_url = urllib.parse.unquote(url)

    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(board.filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

templates/board/board_detail.html
{% extends "user/base.html" %}
{% block contents %}
    <div class="row-mt-5">
        <div class="col-12">
            <div class="card" style="margin-bottom: 10px;">
                {# 제목, 분류, 작성일 #}
                <div class="card-header">
                    <strong>{{ board.title }}</strong><span>[공지사항]</span>
                    <span>{{ board.registered_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body">
                    {# 작성자, 조회수 #}
                    <div>
                        <span>작성자 : {{ board.writer }}</span>
                        <span>조회수 : {{ board.views }}</span>
                    </div>
                    <hr>
                    {% if board.upload_files %}
                        <div class="col-12 text-right">
                            <span style="color: gray">첨부파일 :&nbsp</span>
                            <a id="id_upload_file"
                               href="{% url 'board:board_download' board.id %}">{{ board.filename|truncatechars:25 }}</a>
                        </div>
                    {% endif %}
                    {# 내용 #}
                    <div>
                        {{ board.content | safe }}{# html 태그가 그대로 적용되어 출력되는것을 방지 #}
                    </div>
                </div>
            </div>
            <div>
                {% if board_auth or request.user.level == '0' %}
                    <button class="btn btn-info" onclick="location.href='/board/{{ board.id }}/edit/'">수정</button>
                    <button class="btn btn-info" data-toggle="modal" data-target="#delete_modal">삭제</button>
                    <button class="btn btn-info" onclick="location.href='/board/'">목록으로</button>
                {% else %}
                    <button class="btn btn-info" onclick="location.href='/board/'">목록으로</button>
                {% endif %}
            </div>
        </div>
    </div>
    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">삭제경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>게시글을 삭제하시겠습니까?</p>
                </div>
                <div class="modal-footer">
                    <button onclick="delete_modal()" type="button" class="btn btn-dark">삭제하기</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">취소하기</button>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function delete_modal() {
            location.replace('/board/{{ board.id }}/delete/');
        }
    </script>
{% endblock %}

templates/board/board_list.html
{% extends "user/base.html" %}
{% block contents %}
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">게시판</h4> {# 제목 #}
            {% if q %}
                <h5>'{{ q }}' 검색 결과 입니다.</h5>
            {% endif %}
        </div>
    </div>
    <div>
        <table class="table">
            <thred>
                <tr class="text-center">
                    <th>#</th>
                    <th>title</th>
                    <th>writer</th>
                    <th>date</th>
                    <th>views</th>
                </tr>
                {% if q %}
                {% else %}  {# 공지사항 #}
                {% if board_fixed %}
                {% for board in board_fixed %}
                    <tr class="'text-center" style="cursor:pointer" onclick="location.href='/board/{{ board.id }}'">
                        <td>{{ board.id }}</td>
                        <td>{{ board.title|truncatechars:30 }}</td>
                        {# 30글자보다 크면 ....으로 자름  #}
                        <td>{{ board.writer }}</td>
                        <td>{{ board.registered_date|date:'Y. m. d' }}</td>
                        <td>{{ board.views }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
            {% endif %}
            </thred>
            <tbody>
            {% if board_list %}{# 일반일때 #}
                {% for board in board_list %}
                    <tr class="'text-center" style="cursor:pointer" onclick="location.href='/board/{{ board.id }}'">
                        <td>{{ board.id }}</td>
                        <td>{{ board.title|truncatechars:30 }}</td>
                        {# 30글자보다 크면 ....으로 자름  #}
                        <td>{{ board.writer }}</td>
                        <td>{{ board.registered_date|date:'Y. m. d' }}</td>
                        <td>{{ board.views }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                {% if q %}{# q값 = 검색어 값이 있을떄  #}
                    <tr class="text-center">
                        <td colspan="5">
                            일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                {% else %}
                    <tr class="text-center">
                        <td colspan="5">작성된 게시글이 없습니다</td>
                    </tr>
                {% endif %}
            {% endif %}
            </tbody>
        </table>
    </div>
    {# 검색창 구현 #}
    <div style="margin-top: 30px">
        <form action="" method="GET">
            <div class="col">
                <div class="form-row" style="float: right">
                    <div class="form-row">
                        <div class="col" style="margin-top:10px">
                            <select style="width: 6em" class="custom-select custom-select-sm" name="type">
                                <option value="all">전체</option>
                                <option value="title_content">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="content">내용</option>
                                <option value="writer">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-sm"
                                   style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col" style="margin-top: 8px">
                            <button class="btn btn-info" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div>
            {% if request.user.level == '0' or request.user.level == '1' %}
                <div>
                    <a href="{% url 'board:board_write' %}" class="btn btn-info">글쓰기</a>
                </div>
            {% endif %}
        </div>
        <div class="col-md-6">
            {# Paginated 구현 #}
            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}{#  이전 자료가 있을떄 #}
                        <li class="page-item">
                            <a class="page-link"
                               href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}" tabindex="-1">이전</a>{# type={{ type }}&q={{ q }}&    q값 있을떄  #}
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">이전</a>
                        </li>
                    {% endif %}

                    {% for page in page_range %}
                        <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                            <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}">다음</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">다음</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/board/board_write.html
{% extends "user/base.html" %}


<script type="text/javascript">
    var chectUnload = true;
    $(window).on('beforeunload', function () {
        if (chectUnload) return "이페이지를 나가면 작성된 내용은 저장되지 않습니다."
    })
    $('#write').on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>
{% block contents %}
    <script>
        $(document).ready(function () {
            $('#id_content').summernote({

                placeholder: '내용을 입력해주세요.',
                height: 500,
                minHeight: 500,
                maxHeight: 500,
                lang: 'ko-KR',
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'help']]
                ]

            })
            $('p').css('margin-bottom', '0')
            $('.note-resizebar').css('display', 'none');
        })
        ;
    </script>
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">공지사항</h4>
        </div>
    </div>
    <br>
    <div class="row-mt-5">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card" style="width: 100%">
                <div class="card-header" style="padding: 0rem 0.8rem">
                    <div class="md-form form-group" style="margin-top: 8.5px">
                        <div style="padding: 0  5.5px">
                            {{ form.title }}
                        </div>
                    </div>
                </div>
                <div>
                    {{ form.content }}
                </div>
            </div>
            <div class="card-footer" style="padding-left: 0px; margin-top:18px;">
                <div class="form-group">
                    <div class="col-sm-12">
                        {{ form.upload_files }}
                        <small id="help" class="form-text text-muted" style="margin-bottom: -15px;">
                            &nbsp;&nbsp;[파일 업로드]&nbsp;&nbsp;<i class="fas fa-upload"></i>&nbsp;10MB 이하의 파일만 첨부 가능합니다. 여러
                            파일은
                            압축해서 업로드해주세요.
                        </small>
                    </div>
                </div>
            </div>
            <div class="text-right">
            <button class="btn btn-info"><label style="background-color: rgb(23 ,162, 184); border-radius: .25rem; margin: 0px">
                    {{ form.top_fixed }}
                    <span>상단에 표시하기</span>
                </label></button>
{#                <label style="background-color: rgb(23 ,162, 184); border-radius: .25rem;  padding: 7px 0px; margin: 0px">#}
{#                    {{ form.top_fixed }}#}
{#                    <span>상단에 표시하기</span>#}
{#                </label>#}
                {% if edit %}
                    <button type="submit" class="btn btn-sm">{{ edit }}</button>
                {% else %}
                    <button type="submit" id="write" class="btn btn-info">작성하기</button>
                {% endif %}
                <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none">
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}
    {% if filename %}
        <script type="text/javascript">
            $('[href="{{ file_url }}"]').html('{{ filename }}')
            $('#upload_files-clear_id').css({opacity: '100', position: 'relative', 'pointer-events': 'auto'})

            $('#id_upload_files').change(function () {
                if ($('#id_upload_files').get(0).files.length == 1) {
                    $('.col-sm-12').contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'
                    $('#upload_files-clear_id').attr("checked", false)
                    $('#upload_files-clear_id').prev().hide()
                    $('#upload_files-clear_id').next().hide()
                    $('#upload_files-clear_id').hide()
                }
            })
            $('#upload_files-clear_id').on('click', function () {
                if ($(this).prop('checked')) {
                    $('#id_upload_files').hide()
                    document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'
                } else {
                    $('#id_upload_files').show()
                    document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '
                }
            });

            $('#write').click(function () {
                if ($('#id_upload_files').get(0).files.length == 1) {
                    $('#fileChangeCheck').attr("checked", true)
                }
            });
        </script>
    {% endif %}
{% endblock %}