Django_board/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('free/', include('free.urls')),
    path('', views.home, name='home')
]

board/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.shortcuts import redirect
app_name = 'board'
urlpatterns = [
    path('', views.BoardListView.as_view(), name='board_list'),
    path('<int:pk>/', views.board_detail_view, name='board_detail'),  # 게시글 상세보기
    path('write/', views.board_write_view, name='board_write'),
    path('<int:pk>/edit/', views.board_edit_view, name='board_edit'),
    path('<int:pk>/delete/', views.board_delete_view, name='board_delete'),
    path('download/<int:pk>', views.board_download_view, name='board_download'),
]


#media파일 접근 제한
def protected_file(request, path, document_root=None):
    messages.error(request, '접근불가')
    return redirect('/')


#urlpatterns에 Media File을 제공하는 패턴을 추가하고 protected_file 함수를 구현함으로써 url로 서버상의 MEDIA_ROOT에 접근하는것을 방지합니다.
urlpatterns += static(settings.MEDIA_URL, protected_file, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
from .views import RegisterView, LoginView

urlpatterns = [
    path('', views.home, name='home'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *


# Create your models here.
###level: 사용권한
###auth: 인증번호
class UserManager(BaseUserManager):
    def create_user(self, userid, password, email, **extra):
        if not userid:
            raise ValueError("User must have an userid")
        if not password:
            raise ValueError("User must have an password")

        user = self.model(
            userid= userid,
            password=password,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    #admin 관리자 계정 만들기
    def create_superuser(self, userid, password, email=None):
        user = self.create_user(userid, password, email)

        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0

        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):

    objects = UserManager()

    userid = models.CharField(max_length=32,
                              verbose_name='사용자 ID', unique=True)
    password = models.CharField(max_length=64,
                                verbose_name='비밀번호')
    email = models.EmailField(max_length=64,
                                verbose_name='이메일', unique=True, null=True)
    level = models.CharField(max_length= 18,
                             verbose_name='등급', choices=LEVEL_CHOICES, default=2)
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)


    USERNAME_FIELD = 'userid'
    REQUIRED_FIELDS = ['email']
    def __str__(self):
        return self.userid

    class Meta:
        db_table = 'board_user'
        verbose_name = "게시판 사용자"
        verbose_name_plural = "게시판 사용자"

user/forms.py
from django import forms
from .models import User
from django.contrib.auth.hashers import check_password


class LoginForm(forms.Form):
    userid = forms.CharField(
        error_messages={
            'required': '아이디를 입력해주세요'
    },
        max_length=32, label='사용자 ID'
    )
    password = forms.CharField(
        error_messages={
            'required': '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput, label='비밀번호'
    )
    #유효성 검사
    def clean(self):
        cleaned_data = super().clean()
        userid = cleaned_data.get('userid')
        password = cleaned_data.get('password')

        if userid and password:
            try:
                user = User.objects.get(userid=userid)
            except User.DoesNotExist:
                self.add_error('userid', '아이디가 없습니다')
                return

            if not check_password(password, user.password):
                self.add_error('password', '비밀번호를 틀렸습니다')


class RegisterForm(forms.Form):
    userid = forms.CharField(
        error_messages={
            'required': 'please enter the userid'
        },
        max_length=32, label='사용자 ID'
    )
    password = forms.CharField(
        error_messages={
            'required': 'please enter the password'
        },
        widget=forms.PasswordInput, label='비밀번호'
    )
    re_password = forms.CharField(
        error_messages={
            'required': 'please enter the re_password'
        },
        widget=forms.PasswordInput, label='비밀번호 확인'
    )
    email = forms.EmailField(
        error_messages={
            'required': 'please enter the email'
        },
        max_length=64, label='이메일'
    )
    def clean(self):#유효성 검사
        cleaned_data = super().clean()
        userid = cleaned_data.get('userid')
        password = cleaned_data.get('password')
        re_password = cleaned_data.get('re_password')
        email = cleaned_data.get('email')

        if password and re_password:
            if password != re_password:
                self.add_error('password', 'password, re_password incorrect')
                self.add_error('re_password', 'password, re_password incorrect')

user/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from django.views.generic import FormView
from .models import User
from .decorators import *
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.hashers import make_password


# Create your views here.



def home(request):
    return render(request, '../templates/user/home.html')


# ../templates/user/home.html
class LoginView(FormView):
    template_name = 'user/login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        self.request.session['user'] = form.data.get('userid')

        return super().form_valid(form)


def logout(request):
    if request.session.get('user'):  # 로그인 되어있을때
        del (request.session['user'])  # 로그인한 정보

    return redirect('/')


class RegisterView(FormView):
    template_name = 'user/register.html'
    form_class = RegisterForm
    success_url = '../login'

    def form_valid(self, form):
        user = User(
            userid=form.data.get('userid'),
            password=make_password(form.data.get('password')),
            email=form.data.get('email')
        )
        user.save()
        return super().form_valid(form)

templates/user/base.html
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" /> -->
    {#    <link rel="stylesheet" href="/static/css/bootstrap.min.css"/>#}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
            integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
    {#            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">#}
    {#    </script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    {#    summernote#}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script src="/static/css/summernote.min.css"></script>
    <script src="/static/js/summernote.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="position: relative">
        <div>
            <a class="navbar-brand" onclick=location.href="{% url 'home' %}" style="display: inline">Django Board</a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" onclick=location.href="{% url 'home' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick=location.href="{% url 'board:board_list' %}">Board</a>
                </li>
            {% if request.path == "/free/" or request.path == "/free/free/" or request.path == "/free/question/" or request.path == "/free/information/"%}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size: 14px; padding-top: 10px">
                        분류별로 보기
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url "free:free_list" %}">전체보기</a></li>
                        <li><a class="dropdown-item" href="{% url "free:free_cate_list" %}">자유만 보기</a></li>
                        <li><a class="dropdown-item" href="{% url "free:ques_cate_list" %}">질문만 보기</a></li>
                        <li><a class="dropdown-item" href="{% url "free:info_cate_list" %}">정보만 보기</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if not request.session.user %}
                    <li class="nav-item">
                        <a class="nav-link" onclick=location.href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick=location.href="{% url 'register' %}">Register</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" onclick=location.href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
<div class="container">

    {% block contents %}
    {% endblock %}
</div>
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}
            <script>
                alert("{{ message.message }}") <!-- message alert script -->
            </script>
        {% endif %}
    {% endfor %}
{% endif %}
</body>

</html>

templates/user/home.html
{% extends "user/base.html" %}

{% block contents %}

    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>홈페이지!</h1>
        </div>

    </div>
    <div class="row mt-5">
        {% if request.session.user %}
            <div class="col-12">
                <button class="btn btn-primary btn-block" onclick="location.href='user/logout/'">로그아웃</button>
            </div>
        {% else %}
            <div class="col-6">
                <button class="btn btn-primary btn-block" onclick="location.href='user/login/'">로그인</button>
            </div>
            <div class="col-6">
                <button class="btn btn-primary btn-block" onclick="location.href='user/register/'">회원가입</button>
            </div>
        {% endif %}
    </div>
    <div class="row mt-1">
        <div class="col-12">
            <button class="btn btn-primary btn-block" onclick=location.href='{% url "free:free_list" %}'>게시물 보기</button>
        </div>
    </div>

{% endblock %}

templates/user/login.html
{% extends "user/base.html" %}

{% block contents %}
<div class="row mt-5">
  <div class="col-12 text-center">
    <h1>로그인</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    {{ error }}
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <form method="POST" action=".">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}"
          placeholder="{{ field.label }}" name="{{ field.name }}" />
      </div>
      {% if field.errors %}
      <span style="color: red">{{ field.errors }}</span>
      {% endif %}
      {% endfor %}
      <button type="submit" class="btn btn-primary" onclick="location.href='user/'">로그인</button>
    </form>
  </div>
</div>
{% endblock %}

templates/user/register.html
{% extends "user/base.html" %}

{% block contents %}
    <div class="row mt-5">
        <div class="col-12 text-center">
            <h1>회원가입</h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {{ error }}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            <form method="POST" action=".">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        <input
                                type="{{ field.field.widget.input_type }}"
                                class="form-control"
                                id="{{ field.id_for_label }}"
                                placeholder="{{ field.label }}"
                                name="{{ field.name }}"
                        />
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary" onclick="location.href='../login'">회원가입</button>
            </form>
        </div>
    </div>
{% endblock %}